import { User, Post, Story, Reel, Conversation } from '../types';

export const CURRENT_USER: User = {
  id: 'usr_me',
  username: 'alexrivers',
  name: 'Alex Rivers',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  bio: 'Visual storyteller & Creative technologist ✨ | Tokyo & SF ✈️ | Building the future of social 🚀',
  isVerified: true,
  followersCount: 14200,
  followingCount: 489,
  postsCount: 38,
  website: 'https://yanar.io/alex',
};

export const DEMO_USERS: User[] = [
  {
    id: 'usr_1',
    username: 'elena_lens',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    bio: 'Cinema & analog frames 🎞️ Capturing shadows and neon lights.',
    isVerified: true,
    followersCount: 28400,
    followingCount: 312,
    postsCount: 142,
    isFollowing: true,
  },
  {
    id: 'usr_2',
    username: 'marcus_dev',
    name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    bio: 'Frontend craftsman, WebRTC enthusiast 💻 Coffee & dark mode always.',
    isVerified: false,
    followersCount: 8930,
    followingCount: 540,
    postsCount: 65,
    isFollowing: false,
  },
  {
    id: 'usr_3',
    username: 'sarah_wanderlust',
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    bio: 'Alpine wanderer 🏔️ Chasing sunrises across 40+ countries. Let’s explore.',
    isVerified: true,
    followersCount: 95400,
    followingCount: 620,
    postsCount: 312,
    isFollowing: true,
  },
  {
    id: 'usr_4',
    username: 'neo_beats',
    name: 'Neo Thorne',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    bio: 'Electronic soundscapes & vinyl selector 🎚️ Catch my weekly live sets.',
    isVerified: false,
    followersCount: 15600,
    followingCount: 410,
    postsCount: 89,
    isFollowing: false,
  },
  {
    id: 'usr_5',
    username: 'maya_culinary',
    name: 'Maya Patel',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    bio: 'Plant-forward gastronomy 🥑 Food styling & cozy studio recipes.',
    isVerified: true,
    followersCount: 51200,
    followingCount: 780,
    postsCount: 220,
    isFollowing: true,
  },
];

export const INITIAL_STORIES: Story[] = [
  {
    id: 'story_me',
    user: CURRENT_USER,
    mediaUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    type: 'image',
    hasUnseen: false,
    createdAt: '30m ago',
  },
  {
    id: 'story_1',
    user: DEMO_USERS[0],
    mediaUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80',
    type: 'image',
    hasUnseen: true,
    createdAt: '2h ago',
  },
  {
    id: 'story_2',
    user: DEMO_USERS[2],
    mediaUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    type: 'image',
    hasUnseen: true,
    createdAt: '4h ago',
  },
  {
    id: 'story_3',
    user: DEMO_USERS[1],
    mediaUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    type: 'image',
    hasUnseen: true,
    createdAt: '6h ago',
  },
  {
    id: 'story_4',
    user: DEMO_USERS[3],
    mediaUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    type: 'image',
    hasUnseen: true,
    createdAt: '8h ago',
  },
  {
    id: 'story_5',
    user: DEMO_USERS[4],
    mediaUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80',
    type: 'image',
    hasUnseen: true,
    createdAt: '11h ago',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post_1',
    author: DEMO_USERS[0],
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=85',
    caption: 'Midnight neon vibes in Shibuya. The rain reflections turn the streets into liquid mirrors 🌧️✨ Shot on 35mm f/1.4.',
    location: 'Shibuya, Tokyo, Japan',
    likesCount: 3842,
    commentsCount: 148,
    isLiked: false,
    isSaved: false,
    createdAt: '2 hours ago',
    comments: [
      {
        id: 'c1',
        user: DEMO_USERS[1],
        text: 'The color grading is immaculate! Which film preset is this?',
        createdAt: '1h ago',
        likesCount: 14,
      },
      {
        id: 'c2',
        user: DEMO_USERS[2],
        text: 'Makes me want to hop on the next flight to Tokyo ✈️',
        createdAt: '45m ago',
        likesCount: 8,
      },
    ],
  },
  {
    id: 'post_2',
    author: DEMO_USERS[2],
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=85',
    caption: 'Quiet morning awakening at Yosemite Valley. The fog clearing over the granite monoliths was nothing short of spiritual 🌲⛰️',
    location: 'Yosemite National Park, California',
    likesCount: 6120,
    commentsCount: 231,
    isLiked: true,
    isSaved: true,
    createdAt: '5 hours ago',
    comments: [
      {
        id: 'c3',
        user: CURRENT_USER,
        text: 'Incredible lighting! That 6am wake up was definitely worth it.',
        createdAt: '3h ago',
        likesCount: 19,
      },
      {
        id: 'c4',
        user: DEMO_USERS[3],
        text: 'Pure peace. Frame worthy shot!',
        createdAt: '2h ago',
        likesCount: 6,
      },
    ],
  },
  {
    id: 'post_3',
    author: CURRENT_USER,
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=85',
    caption: 'Building the next evolution of social connectivity with the team today. Super excited to show what we have been crafting with WebRTC audio/video! 🚀🔥',
    location: 'YANAR HQ, San Francisco',
    likesCount: 1240,
    commentsCount: 52,
    isLiked: true,
    isSaved: false,
    createdAt: '1 day ago',
    comments: [
      {
        id: 'c5',
        user: DEMO_USERS[1],
        text: 'WebRTC in the browser feels like magic when it connects smoothly ⚡',
        createdAt: '18h ago',
        likesCount: 11,
      },
    ],
  },
  {
    id: 'post_4',
    author: DEMO_USERS[4],
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=85',
    caption: 'Colorful superfood nourish bowl with sesame-crusted tofu, pickled radishes, and creamy tahini drizzle 🥗✨ Healthy fuel for creation.',
    location: 'SoHo, New York',
    likesCount: 4180,
    commentsCount: 89,
    isLiked: false,
    isSaved: false,
    createdAt: '1 day ago',
    comments: [
      {
        id: 'c6',
        user: DEMO_USERS[0],
        text: 'Looks too pretty to eat! Can you share the tahini dressing ratio?',
        createdAt: '22h ago',
        likesCount: 5,
      },
    ],
  },
];

export const INITIAL_REELS: Reel[] = [
  {
    id: 'reel_1',
    author: DEMO_USERS[0],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-taking-photos-of-a-model-in-a-studio-41440-large.mp4',
    caption: 'Studio lighting setups that will elevate your portrait game in 30 seconds 📸⚡',
    audioTrack: 'Elena Rostova • Original Audio (Tokyo Chill)',
    likesCount: 18400,
    commentsCount: 642,
    sharesCount: 1240,
    isLiked: false,
    isSaved: false,
    createdAt: '3h ago',
  },
  {
    id: 'reel_2',
    author: DEMO_USERS[2],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-city-traffic-at-night-42407-large.mp4',
    caption: 'Night hyperlapse over the skyline. Look at those endless light arteries 🌃🚗',
    audioTrack: 'Neo Thorne • Synth Wave Echoes',
    likesCount: 34900,
    commentsCount: 1120,
    sharesCount: 4520,
    isLiked: true,
    isSaved: true,
    createdAt: '1d ago',
  },
  {
    id: 'reel_3',
    author: DEMO_USERS[3],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-man-playing-on-a-synthesizer-41398-large.mp4',
    caption: 'Analog synthesizer modular jam sessions. Which patch cord is your favorite? 🎹🎛️',
    audioTrack: 'Neo Thorne • Modular Sunrise Jam',
    likesCount: 12300,
    commentsCount: 419,
    sharesCount: 920,
    isLiked: false,
    isSaved: false,
    createdAt: '2d ago',
  },
  {
    id: 'reel_4',
    author: DEMO_USERS[4],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-cutting-vegetables-on-a-wooden-board-42861-large.mp4',
    caption: 'Knife skills 101: Uniform julienne cuts will change how your stir fry cooks! 🥕🔪',
    audioTrack: 'Maya Patel • Lo-fi Kitchen Beats',
    likesCount: 27800,
    commentsCount: 840,
    sharesCount: 3100,
    isLiked: true,
    isSaved: false,
    createdAt: '3d ago',
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    participant: DEMO_USERS[0],
    unreadCount: 2,
    isOnline: true,
    typing: false,
    messages: [
      {
        id: 'm1',
        senderId: DEMO_USERS[0].id,
        text: 'Hey Alex! Loved your latest shot of the studio setup.',
        createdAt: '10:45 AM',
        status: 'read',
      },
      {
        id: 'm2',
        senderId: 'usr_me',
        text: 'Thank you Elena! Trying out the new anamorphic prime lenses.',
        createdAt: '10:48 AM',
        status: 'read',
      },
      {
        id: 'm3',
        senderId: DEMO_USERS[0].id,
        text: 'Are you free for a quick video call to review the lookbook drafts?',
        createdAt: '11:02 AM',
        status: 'delivered',
      },
      {
        id: 'm4',
        senderId: DEMO_USERS[0].id,
        mediaUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=600&q=80',
        mediaType: 'image',
        text: 'Here is the draft hero shot we are aiming for!',
        createdAt: '11:03 AM',
        status: 'delivered',
      },
    ],
  },
  {
    id: 'conv_2',
    participant: DEMO_USERS[1],
    unreadCount: 0,
    isOnline: true,
    typing: false,
    messages: [
      {
        id: 'm2_1',
        senderId: DEMO_USERS[1].id,
        text: 'WebRTC data channels are performing smoothly under testing!',
        createdAt: 'Yesterday',
        status: 'read',
      },
      {
        id: 'm2_2',
        senderId: 'usr_me',
        text: 'Awesome! Let’s test the audio and screen sharing flow together.',
        createdAt: 'Yesterday',
        status: 'read',
      },
    ],
  },
  {
    id: 'conv_3',
    participant: DEMO_USERS[2],
    unreadCount: 0,
    isOnline: false,
    typing: false,
    messages: [
      {
        id: 'm3_1',
        senderId: DEMO_USERS[2].id,
        text: 'Yosemite permits just opened up for next month if you want to join!',
        createdAt: '2d ago',
        status: 'read',
      },
      {
        id: 'm3_2',
        senderId: 'usr_me',
        text: 'Count me in! Packing the drone and hiking boots.',
        createdAt: '2d ago',
        status: 'read',
      },
    ],
  },
  {
    id: 'conv_4',
    participant: DEMO_USERS[3],
    unreadCount: 0,
    isOnline: false,
    typing: false,
    messages: [
      {
        id: 'm4_1',
        senderId: DEMO_USERS[3].id,
        text: 'Sent you the master stems for the background track on the new reel.',
        createdAt: '3d ago',
        status: 'read',
      },
    ],
  },
];
